### ISSUE TITLE
regular lanterns look too saturated blue in most angles

### ISSUE THREAD

**Issue by hematite0** [ClassicFaithful/64x-Jappa#2]
![Screenshot 2023-04-16 010542](https://user-images.githubusercontent.com/121654172/232259269-280c14cd-21e9-4524-82c3-3e4a6a499617.png)

( in bedrock edition )

**Comment by 3vorp** [comment]
a) we have a bedrock edition repository to report these bugs on
b) this isn't even classic faithful 64x, this is faithful 64x — the repo can be found at https://github.com/faithful-resource-pack/faithful-bedrock-64x
