### ISSUE TITLE
underwater foliage like kelp and seagrass have box around them within a certain distance

### ISSUE THREAD

**Issue by hematite0** [ClassicFaithful/64x-Jappa#3]
![image](https://user-images.githubusercontent.com/121654172/232259401-9ffac491-38f0-42a5-9c78-316fc868d068.png)

**Comment by Pomi108** [comment]
To whoever decides to fix this: It's caused by a wrong TGA setup. Make sure all the transparent pixels have their alpha value set to 0.

**Comment by 3vorp** [comment]
this is faithful 64, not classic faithful 64

the correct repository to report these bugs can be found at https://github.com/faithful-resource-pack/faithful-java-64x
